version: 1.5.10-{build}
configuration: Release
platform:
- Win32
shallow_clone: true
environment:
  DXSDK: '%DXSDK_DIR%'
before_build:
- cmd: >-
    echo %PLATFORM%

    echo %CONFIGURATION%

    echo cop_%APPVEYOR_REPO_TAG_NAME%_%PLATFORM%.7z
build:
  project: ./engine.sln
  verbosity: minimal
after_build:
- cmd: >-
    set COR_PLAT=%PLATFORM%

    IF "%COR_PLAT%" == "Win32" set COR_PLAT=x86

    md dist

    echo ===================== engine files =====================

    md dist\engine

    copy opt\start_%COR_PLAT%.bat dist\engine

    md dist\engine\bin_%COR_PLAT%

    copy intermediate\%PLATFORM%-%CONFIGURATION%\*.exe dist\engine\bin_%COR_PLAT%\

    copy intermediate\%PLATFORM%-%CONFIGURATION%\*.dll dist\engine\bin_%COR_PLAT%\

    md dist\engine\gamedata

    xcopy gamedata dist\engine\gamedata /S /E

    7z a cop_%APPVEYOR_REPO_TAG_NAME%_%COR_PLAT%.7z dist\engine\*

    echo appveyor PushArtifact cop_%APPVEYOR_REPO_TAG_NAME%_%COR_PLAT%.7z release

    echo ===================== engine pdb files =====================

    md dist\engine_pdb_%COR_PLAT%

    copy intermediate\%PLATFORM%-%CONFIGURATION%\*.pdb dist\engine_pdb_%COR_PLAT%\

    7z a cop_%APPVEYOR_REPO_TAG_NAME%_%COR_PLAT%_pdb.7z dist\engine_pdb_%COR_PLAT%\*
artifacts:
- path: .\cop_$(appveyor_repo_tag_name)_$(cor_plat).7z
  name: release
- path: .\cop_$(appveyor_repo_tag_name)_$(cor_plat)_pdb.7z
  name: release
deploy:
- provider: GitHub
  auth_token:
    secure: pXJeBrB1oq+/lPsy2jphy4dRQ542dkJRbAEOD3y/YgSVsoRTSgIt01EI92q9whrl
  artifact: release
  on:
    appveyor_repo_tag: true